// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyBudget.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyBudget.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MyBudgetDbContext))]
    partial class MyBudgetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyBudget.Domain.Budgets.BudgetDefault", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<short>("EffectiveFromMonth")
                        .HasColumnType("smallint")
                        .HasColumnName("effective_from_month");

                    b.Property<short>("EffectiveFromYear")
                        .HasColumnType("smallint")
                        .HasColumnName("effective_from_year");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("uq_budget_defaults_user_category");

                    b.ToTable("budget_defaults", null, t =>
                        {
                            t.HasCheckConstraint("ck_budget_defaults_amount", "amount >= 0");

                            t.HasCheckConstraint("ck_budget_defaults_month", "effective_from_month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("ck_budget_defaults_year", "effective_from_year BETWEEN 2000 AND 2100");
                        });
                });

            modelBuilder.Entity("MyBudget.Domain.Budgets.MonthlyBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<short>("Month")
                        .HasColumnType("smallint")
                        .HasColumnName("month");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("uq_monthly_budgets_period");

                    b.ToTable("monthly_budgets", null, t =>
                        {
                            t.HasCheckConstraint("ck_monthly_budgets_month", "month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("ck_monthly_budgets_year", "year BETWEEN 2000 AND 2100");
                        });
                });

            modelBuilder.Entity("MyBudget.Domain.Budgets.MonthlyBudgetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MonthlyBudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("monthly_budget_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("MonthlyBudgetId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("uq_monthly_budget_categories_budget_category");

                    b.ToTable("monthly_budget_categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_monthly_budget_categories_amount", "amount >= 0");
                        });
                });

            modelBuilder.Entity("MyBudget.Domain.Categories.BudgetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_icon", "char_length(icon) <= 16");

                            t.HasCheckConstraint("ck_categories_name", "btrim(name) <> '' AND char_length(name) <= 60");
                        });
                });

            modelBuilder.Entity("MyBudget.Domain.Categories.CategoryAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("alias");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("NormalizedAlias")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("normalized_alias");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "NormalizedAlias")
                        .IsUnique()
                        .HasDatabaseName("uq_category_aliases_category_normalized");

                    b.HasIndex("UserId", "NormalizedAlias")
                        .HasDatabaseName("ix_category_aliases_user_normalized");

                    b.ToTable("category_aliases", null, t =>
                        {
                            t.HasCheckConstraint("ck_category_aliases_alias", "btrim(alias) <> '' AND char_length(alias) <= 60");
                        });
                });

            modelBuilder.Entity("MyBudget.Domain.Expenses.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<string>("CategorizationSource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("categorization_source");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date")
                        .HasColumnName("expense_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CategoryId", "ExpenseDate")
                        .HasDatabaseName("ix_expenses_user_category_date");

                    b.HasIndex("UserId", "ExpenseDate", "Id")
                        .IsDescending(false, true, true)
                        .HasDatabaseName("ix_expenses_user_date");

                    b.ToTable("expenses", null, t =>
                        {
                            t.HasCheckConstraint("ck_expenses_amount", "amount > 0 AND amount <= 999999999999");

                            t.HasCheckConstraint("ck_expenses_description", "description IS NULL OR char_length(description) <= 500");

                            t.HasCheckConstraint("ck_expenses_source", "categorization_source IN ('manual','matched','ambiguous','learned')");
                        });
                });

            modelBuilder.Entity("MyBudget.Domain.Recurring.RecurringExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<short>("DayOfMonth")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_month");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateOnly?>("LastGeneratedDate")
                        .HasColumnType("date")
                        .HasColumnName("last_generated_date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("ix_recurring_expenses_user_active");

                    b.ToTable("recurring_expenses", null, t =>
                        {
                            t.HasCheckConstraint("ck_recurring_expenses_amount", "amount > 0 AND amount <= 999999999999");

                            t.HasCheckConstraint("ck_recurring_expenses_day", "day_of_month BETWEEN 1 AND 31");

                            t.HasCheckConstraint("ck_recurring_expenses_description", "description IS NULL OR char_length(description) <= 500");

                            t.HasCheckConstraint("ck_recurring_expenses_period", "end_date IS NULL OR end_date >= start_date");
                        });
                });

            modelBuilder.Entity("MyBudget.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<bool>("DailyReminderEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("daily_reminder_enabled");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("language");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique()
                        .HasDatabaseName("uq_users_telegram_user_id");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_currency", "currency ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_users_language", "language ~ '^[a-z]{2}(-[A-Z]{2})?$'");
                        });
                });

            modelBuilder.Entity("MyBudget.Infrastructure.Persistence.Records.BudgetAlertRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<short>("Month")
                        .HasColumnType("smallint")
                        .HasColumnName("month");

                    b.Property<DateTimeOffset>("NotifiedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("notified_at");

                    b.Property<short>("Threshold")
                        .HasColumnType("smallint")
                        .HasColumnName("threshold");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CategoryId", "Year", "Month", "Threshold")
                        .IsUnique()
                        .HasDatabaseName("uq_budget_alerts_user_category_period_threshold");

                    b.ToTable("budget_alerts", null, t =>
                        {
                            t.HasCheckConstraint("ck_budget_alerts_month", "month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("ck_budget_alerts_threshold", "threshold IN (80, 100)");

                            t.HasCheckConstraint("ck_budget_alerts_year", "year BETWEEN 2000 AND 2100");
                        });
                });

            modelBuilder.Entity("MyBudget.Infrastructure.Persistence.Records.ConversationStateRecord", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("ChatId")
                        .HasColumnType("bigint")
                        .HasColumnName("chat_id");

                    b.Property<string>("Conversation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("conversation");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("conversation_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_conversation_states_non_empty", "btrim(conversation) <> '' AND btrim(state) <> ''");
                        });
                });

            modelBuilder.Entity("MyBudget.Infrastructure.Persistence.Records.MonthlyClosingRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Month")
                        .HasColumnType("smallint")
                        .HasColumnName("month");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("uq_monthly_closings_user_period");

                    b.ToTable("monthly_closings", null, t =>
                        {
                            t.HasCheckConstraint("ck_monthly_closings_month", "month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("ck_monthly_closings_year", "year BETWEEN 2000 AND 2100");
                        });
                });

            modelBuilder.Entity("MyBudget.Infrastructure.Persistence.Records.PendingActionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_pending_actions_expires_at");

                    b.HasIndex("UserId");

                    b.ToTable("pending_actions", null, t =>
                        {
                            t.HasCheckConstraint("ck_pending_actions_non_empty", "btrim(action) <> ''");
                        });
                });

            modelBuilder.Entity("MyBudget.Infrastructure.Persistence.Records.ReminderDeliveryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("sent_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Kind", "LocalDate")
                        .IsUnique()
                        .HasDatabaseName("uq_reminder_deliveries_user_kind_date");

                    b.ToTable("reminder_deliveries", null, t =>
                        {
                            t.HasCheckConstraint("ck_reminder_deliveries_kind", "btrim(kind) <> ''");
                        });
                });

            modelBuilder.Entity("MyBudget.Infrastructure.Persistence.Records.TelegramUpdateRecord", b =>
                {
                    b.Property<long>("UpdateId")
                        .HasColumnType("bigint")
                        .HasColumnName("update_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("UpdateId");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_telegram_updates_received_at");

                    b.HasIndex("UserId");

                    b.ToTable("telegram_updates", null, t =>
                        {
                            t.HasCheckConstraint("ck_telegram_updates_status", "status IN ('received','processed','failed','ignored')");
                        });
                });

            modelBuilder.Entity("MyBudget.Domain.Budgets.BudgetDefault", b =>
                {
                    b.HasOne("MyBudget.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyBudget.Domain.Budgets.MonthlyBudget", b =>
                {
                    b.HasOne("MyBudget.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyBudget.Domain.Budgets.MonthlyBudgetCategory", b =>
                {
                    b.HasOne("MyBudget.Domain.Budgets.MonthlyBudget", null)
                        .WithMany("Allocations")
                        .HasForeignKey("MonthlyBudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyBudget.Domain.Categories.BudgetCategory", b =>
                {
                    b.HasOne("MyBudget.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyBudget.Domain.Categories.CategoryAlias", b =>
                {
                    b.HasOne("MyBudget.Domain.Categories.BudgetCategory", null)
                        .WithMany("Aliases")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyBudget.Domain.Expenses.Expense", b =>
                {
                    b.HasOne("MyBudget.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyBudget.Domain.Recurring.RecurringExpense", b =>
                {
                    b.HasOne("MyBudget.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyBudget.Infrastructure.Persistence.Records.BudgetAlertRecord", b =>
                {
                    b.HasOne("MyBudget.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyBudget.Infrastructure.Persistence.Records.ConversationStateRecord", b =>
                {
                    b.HasOne("MyBudget.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyBudget.Infrastructure.Persistence.Records.MonthlyClosingRecord", b =>
                {
                    b.HasOne("MyBudget.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyBudget.Infrastructure.Persistence.Records.PendingActionRecord", b =>
                {
                    b.HasOne("MyBudget.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyBudget.Infrastructure.Persistence.Records.ReminderDeliveryRecord", b =>
                {
                    b.HasOne("MyBudget.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyBudget.Infrastructure.Persistence.Records.TelegramUpdateRecord", b =>
                {
                    b.HasOne("MyBudget.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MyBudget.Domain.Budgets.MonthlyBudget", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("MyBudget.Domain.Categories.BudgetCategory", b =>
                {
                    b.Navigation("Aliases");
                });
#pragma warning restore 612, 618
        }
    }
}
