using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MyBudget.Domain.Categories;

namespace MyBudget.Infrastructure.Persistence.Configurations;

internal sealed class CategoryAliasConfiguration : IEntityTypeConfiguration<CategoryAlias>
{
    public void Configure(EntityTypeBuilder<CategoryAlias> builder)
    {
        builder.ToTable("category_aliases", table =>
        {
            table.HasCheckConstraint(
                "ck_category_aliases_alias",
                "btrim(alias) <> '' AND char_length(alias) <= 60");
        });

        builder.HasKey(alias => alias.Id);

        builder.Property(alias => alias.Id)
            .HasColumnName("id")
            // Generated by the store: see Entity(bool keyGeneratedByStore) for why an
            // aggregate-created record must not carry a client-assigned key.
            .ValueGeneratedOnAdd();
        builder.Property(alias => alias.UserId).HasColumnName("user_id").IsRequired();
        builder.Property(alias => alias.CategoryId).HasColumnName("category_id").IsRequired();
        builder.Property(alias => alias.Alias).HasColumnName("alias").HasMaxLength(60).IsRequired();
        builder.Property(alias => alias.NormalizedAlias).HasColumnName("normalized_alias").HasMaxLength(60).IsRequired();
        builder.Property(alias => alias.CreatedAt).HasColumnName("created_at").HasColumnType("timestamptz").IsRequired();
        builder.Property(alias => alias.UpdatedAt).HasColumnName("updated_at").HasColumnType("timestamptz").IsRequired();

        builder
            .HasIndex(alias => new { alias.CategoryId, alias.NormalizedAlias })
            .IsUnique()
            .HasDatabaseName("uq_category_aliases_category_normalized");

        builder
            .HasIndex(alias => new { alias.UserId, alias.NormalizedAlias })
            .HasDatabaseName("ix_category_aliases_user_normalized");
    }
}
