using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MyBudget.Domain.Budgets;

namespace MyBudget.Infrastructure.Persistence.Configurations;

internal sealed class MonthlyBudgetCategoryConfiguration : IEntityTypeConfiguration<MonthlyBudgetCategory>
{
    public void Configure(EntityTypeBuilder<MonthlyBudgetCategory> builder)
    {
        builder.ToTable("monthly_budget_categories", table =>
            table.HasCheckConstraint("ck_monthly_budget_categories_amount", "amount >= 0"));

        builder.HasKey(allocation => allocation.Id);

        builder.Property(allocation => allocation.Id)
            .HasColumnName("id")
            // Generated by the store: see Entity(bool keyGeneratedByStore) for why an
            // aggregate-created record must not carry a client-assigned key.
            .ValueGeneratedOnAdd();
        builder.Property(allocation => allocation.UserId).HasColumnName("user_id").IsRequired();
        builder.Property(allocation => allocation.MonthlyBudgetId).HasColumnName("monthly_budget_id").IsRequired();
        builder.Property(allocation => allocation.CategoryId).HasColumnName("category_id").IsRequired();
        builder.Property(allocation => allocation.Amount).HasColumnName("amount").HasColumnType("bigint").IsRequired();
        builder.Property(allocation => allocation.CreatedAt).HasColumnName("created_at").HasColumnType("timestamptz").IsRequired();
        builder.Property(allocation => allocation.UpdatedAt).HasColumnName("updated_at").HasColumnType("timestamptz").IsRequired();

        builder
            .HasIndex(allocation => new { allocation.MonthlyBudgetId, allocation.CategoryId })
            .IsUnique()
            .HasDatabaseName("uq_monthly_budget_categories_budget_category");

        // The cross-user guarantees live in the database, not in EF's model:
        //   (monthly_budget_id, user_id) -> monthly_budgets (id, user_id)
        //   (category_id,       user_id) -> categories      (id, user_id)
        // Both are created by the InitialSchema migration with migrationBuilder.Sql(...).
    }
}
