using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MyBudget.Domain.Users;
using MyBudget.Infrastructure.Persistence.Records;

namespace MyBudget.Infrastructure.Persistence.Configurations;

internal sealed class TelegramUpdateRecordConfiguration : IEntityTypeConfiguration<TelegramUpdateRecord>
{
    public void Configure(EntityTypeBuilder<TelegramUpdateRecord> builder)
    {
        builder.ToTable("telegram_updates", table => table.HasCheckConstraint(
            "ck_telegram_updates_status",
            "status IN ('received','processed','failed','ignored')"));

        builder.HasKey(record => record.UpdateId);

        // The key comes from Telegram, so it is never generated here.
        builder.Property(record => record.UpdateId)
            .HasColumnName("update_id")
            .ValueGeneratedNever();
        builder.Property(record => record.UserId).HasColumnName("user_id");
        builder.Property(record => record.ReceivedAt).HasColumnName("received_at").HasColumnType("timestamptz").IsRequired();
        builder.Property(record => record.ProcessedAt).HasColumnName("processed_at").HasColumnType("timestamptz");
        builder.Property(record => record.Status).HasColumnName("status").HasMaxLength(16).IsRequired();
        builder.Property(record => record.Attempts).HasColumnName("attempts").IsRequired();
        builder.Property(record => record.LastError).HasColumnName("last_error").HasMaxLength(500);

        builder
            .HasIndex(record => record.ReceivedAt)
            .HasDatabaseName("ix_telegram_updates_received_at");

        // Deleting a user must not lose the operational trail of what Telegram delivered.
        builder
            .HasOne<User>()
            .WithMany()
            .HasForeignKey(record => record.UserId)
            .OnDelete(DeleteBehavior.SetNull);
    }
}

internal sealed class ConversationStateRecordConfiguration : IEntityTypeConfiguration<ConversationStateRecord>
{
    public void Configure(EntityTypeBuilder<ConversationStateRecord> builder)
    {
        builder.ToTable("conversation_states", table => table.HasCheckConstraint(
            "ck_conversation_states_non_empty",
            "btrim(conversation) <> '' AND btrim(state) <> ''"));

        builder.HasKey(record => record.UserId);

        builder.Property(record => record.UserId).HasColumnName("user_id").ValueGeneratedNever();
        builder.Property(record => record.ChatId).HasColumnName("chat_id").IsRequired();
        builder.Property(record => record.Conversation).HasColumnName("conversation").HasMaxLength(64).IsRequired();
        builder.Property(record => record.State).HasColumnName("state").HasMaxLength(64).IsRequired();
        builder.Property(record => record.Payload).HasColumnName("payload").HasColumnType("jsonb").IsRequired();
        builder.Property(record => record.ExpiresAt).HasColumnName("expires_at").HasColumnType("timestamptz").IsRequired();
        builder.Property(record => record.CreatedAt).HasColumnName("created_at").HasColumnType("timestamptz").IsRequired();
        builder.Property(record => record.UpdatedAt).HasColumnName("updated_at").HasColumnType("timestamptz").IsRequired();

        builder
            .HasOne<User>()
            .WithMany()
            .HasForeignKey(record => record.UserId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}

internal sealed class PendingActionRecordConfiguration : IEntityTypeConfiguration<PendingActionRecord>
{
    public void Configure(EntityTypeBuilder<PendingActionRecord> builder)
    {
        builder.ToTable("pending_actions", table => table.HasCheckConstraint(
            "ck_pending_actions_non_empty",
            "btrim(action) <> ''"));

        // The identifier is generated by the application and embedded in callback data, so it is
        // never generated by the store.
        builder.HasKey(record => record.Id);
        builder.Property(record => record.Id).HasColumnName("id").ValueGeneratedNever();
        builder.Property(record => record.UserId).HasColumnName("user_id").IsRequired();
        builder.Property(record => record.Action).HasColumnName("action").HasMaxLength(64).IsRequired();
        builder.Property(record => record.Payload).HasColumnName("payload").HasColumnType("jsonb").IsRequired();
        builder.Property(record => record.ConsumedAt).HasColumnName("consumed_at").HasColumnType("timestamptz");
        builder.Property(record => record.ExpiresAt).HasColumnName("expires_at").HasColumnType("timestamptz").IsRequired();
        builder.Property(record => record.CreatedAt).HasColumnName("created_at").HasColumnType("timestamptz").IsRequired();

        builder
            .HasIndex(record => record.ExpiresAt)
            .HasDatabaseName("ix_pending_actions_expires_at");

        // A draft has no meaning without its owner, so deleting the user takes it along.
        builder
            .HasOne<User>()
            .WithMany()
            .HasForeignKey(record => record.UserId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}

internal sealed class BudgetAlertRecordConfiguration : IEntityTypeConfiguration<BudgetAlertRecord>
{
    public void Configure(EntityTypeBuilder<BudgetAlertRecord> builder)
    {
        builder.ToTable("budget_alerts", table =>
        {
            table.HasCheckConstraint("ck_budget_alerts_month", "month BETWEEN 1 AND 12");
            table.HasCheckConstraint("ck_budget_alerts_year", "year BETWEEN 2000 AND 2100");
            table.HasCheckConstraint("ck_budget_alerts_threshold", "threshold IN (80, 100)");
        });

        builder.HasKey(record => record.Id);
        builder.Property(record => record.Id).HasColumnName("id").ValueGeneratedNever();
        builder.Property(record => record.UserId).HasColumnName("user_id").IsRequired();
        builder.Property(record => record.CategoryId).HasColumnName("category_id").IsRequired();
        builder.Property(record => record.Year).HasColumnName("year").HasColumnType("smallint").IsRequired();
        builder.Property(record => record.Month).HasColumnName("month").HasColumnType("smallint").IsRequired();
        builder.Property(record => record.Threshold).HasColumnName("threshold").HasColumnType("smallint").IsRequired();
        builder.Property(record => record.NotifiedAt).HasColumnName("notified_at").HasColumnType("timestamptz").IsRequired();

        builder
            .HasIndex(record => new
            {
                record.UserId,
                record.CategoryId,
                record.Year,
                record.Month,
                record.Threshold,
            })
            .IsUnique()
            .HasDatabaseName("uq_budget_alerts_user_category_period_threshold");

        builder
            .HasOne<User>()
            .WithMany()
            .HasForeignKey(record => record.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        // The same-user guarantee for the category reference is a composite foreign key
        // created by the BudgetAlerts migration:
        //   (category_id, user_id) -> categories (id, user_id)
    }
}

internal sealed class MonthlyClosingRecordConfiguration : IEntityTypeConfiguration<MonthlyClosingRecord>
{
    public void Configure(EntityTypeBuilder<MonthlyClosingRecord> builder)
    {
        builder.ToTable("monthly_closings", table =>
        {
            table.HasCheckConstraint("ck_monthly_closings_month", "month BETWEEN 1 AND 12");
            table.HasCheckConstraint("ck_monthly_closings_year", "year BETWEEN 2000 AND 2100");
        });

        builder.HasKey(record => record.Id);
        builder.Property(record => record.Id).HasColumnName("id").ValueGeneratedNever();
        builder.Property(record => record.UserId).HasColumnName("user_id").IsRequired();
        builder.Property(record => record.Year).HasColumnName("year").HasColumnType("smallint").IsRequired();
        builder.Property(record => record.Month).HasColumnName("month").HasColumnType("smallint").IsRequired();
        builder.Property(record => record.SentAt).HasColumnName("sent_at").HasColumnType("timestamptz").IsRequired();

        builder
            .HasIndex(record => new { record.UserId, record.Year, record.Month })
            .IsUnique()
            .HasDatabaseName("uq_monthly_closings_user_period");

        // A closing has no meaning without its owner, so deleting the user takes it along.
        builder
            .HasOne<User>()
            .WithMany()
            .HasForeignKey(record => record.UserId)
            .OnDelete(DeleteBehavior.Cascade);
    }
}
